package com.membaza.api.email.persistence;

/**
 * @author Emil Forslund
 * @since 1.0.0
 */
public enum Privilege {

    CREATE_API_KEYS_PRIVILEGE,
    UPDATE_API_KEYS_PRIVILEGE, 
    DELETE_API_KEYS_PRIVILEGE,
    READ_API_KEYS_PRIVILEGE,

    CREATE_TEMPLATES_PRIVILEGE,
    UPDATE_TEMPLATES_PRIVILEGE,
    DELETE_TEMPLATES_PRIVILEGE,
    READ_TEMPLATES_PRIVILEGE,

    CREATE_LISTS_PRIVILEGE,
    UPDATE_LISTS_PRIVILEGE,
    DELETE_LISTS_PRIVILEGE,
    READ_LISTS_PRIVILEGE,

    CREATE_OPTIONS_PRIVILEGE,
    UPDATE_OPTIONS_PRIVILEGE,
    DELETE_OPTIONS_PRIVILEGE,
    READ_OPTIONS_PRIVILEGE,

    SEND_EMAIL_PRIVILEGE

}
